from datetime import date
from decimal import Decimal

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.db.models import Sum
from django.utils import timezone
from datetime import timedelta

from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.lib.colors import HexColor

from .models import (
    Loan,
    Payment,
    Borrower,
    RepaymentSchedule,
    CompanySettings,
)


PAGE_WIDTH = 595
PAGE_HEIGHT = 842


def company():
    return CompanySettings.objects.first()


def draw_header(pdf, title):

    c = company()

    if c and c.logo:
        try:
            logo = ImageReader(c.logo.path)

            pdf.drawImage(
                logo,
                40,
                PAGE_HEIGHT - 80,
                width=55,
                height=55,
                preserveAspectRatio=True,
                mask="auto"
            )
        except Exception:
            pass

    pdf.setFont("Helvetica-Bold", 18)

    pdf.drawString(
        110,
        PAGE_HEIGHT - 40,
        c.company_name if c else "COUNTRYWIDE LENDING & SERVICES"
    )

    pdf.setFont("Helvetica", 9)

    if c:

        if c.address:
            pdf.drawString(
                110,
                PAGE_HEIGHT - 56,
                c.address
            )

        if c.phone:
            pdf.drawString(
                110,
                PAGE_HEIGHT - 69,
                f"Phone: {c.phone}"
            )

        if c.email:
            pdf.drawString(
                110,
                PAGE_HEIGHT - 82,
                f"Email: {c.email}"
            )

    pdf.setStrokeColor(HexColor("#0B5ED7"))

    pdf.line(
        40,
        PAGE_HEIGHT - 96,
        PAGE_WIDTH - 40,
        PAGE_HEIGHT - 96
    )

    pdf.setFont("Helvetica-Bold", 15)

    pdf.drawCentredString(
        PAGE_WIDTH / 2,
        PAGE_HEIGHT - 118,
        title
    )

    pdf.setFont("Helvetica", 9)

    pdf.drawRightString(
        PAGE_WIDTH - 40,
        PAGE_HEIGHT - 118,
        date.today().strftime("%d %B %Y")
    )

    return 680


def draw_footer(pdf, request):

    c = company()

    pdf.line(
        40,
        60,
        PAGE_WIDTH - 40,
        60
    )

    pdf.setFont("Helvetica", 8)

    pdf.drawString(
        40,
        45,
        c.report_footer if c and c.report_footer else "Generated by CountryWide Lending System"
    )

    pdf.drawRightString(
        PAGE_WIDTH - 40,
        45,
        f"Printed by: {request.user.get_full_name() or request.user.username}"
    )

    pdf.drawCentredString(
        PAGE_WIDTH / 2,
        25,
        f"© {date.today().year} {c.company_name if c else 'CountryWide Lending'}"
    )

def loan_statement_pdf(request, loan_id):

    loan = get_object_or_404(
        Loan.objects.select_related("borrower"),
        id=loan_id
    )

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        f'attachment; filename="Loan_Statement_{loan.id}.pdf"'
    )

    pdf = canvas.Canvas(response)

    y = draw_header(pdf, "LOAN STATEMENT")

    borrower = loan.borrower

    # ============================================
    # BORROWER INFORMATION
    # ============================================

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(40, y, "Borrower Information")

    y -= 25

    pdf.setFont("Helvetica", 10)

    pdf.drawString(
        50,
        y,
        f"Borrower Name : {borrower.first_name} {borrower.last_name}"
    )

    y -= 20

    pdf.drawString(
        50,
        y,
        f"Phone : {borrower.phone}"
    )

    y -= 20

    if borrower.address:
        pdf.drawString(
            50,
            y,
            f"Address : {borrower.address}"
        )
        y -= 20

    if borrower.nin:
        pdf.drawString(
            50,
            y,
            f"NIN : {borrower.nin}"
        )
        y -= 20

    if borrower.bvn:
        pdf.drawString(
            50,
            y,
            f"BVN : {borrower.bvn}"
        )
        y -= 25

    # ============================================
    # LOAN INFORMATION
    # ============================================

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(40, y, "Loan Information")

    y -= 25

    pdf.setFont("Helvetica", 10)

    pdf.drawString(
        50,
        y,
        f"Loan ID : {loan.id}"
    )

    y -= 20

    pdf.drawString(
        50,
        y,
        f"Loan Amount : {{ company.currency_symbol }}{loan.loan_amount:,.2f}"
    )

    y -= 20

    pdf.drawString(
        50,
        y,
        f"Interest Rate : {loan.interest_rate}%"
    )

    y -= 20

    pdf.drawString(
        50,
        y,
        f"Duration : {loan.duration_weeks} Weeks"
    )

    y -= 20

    pdf.drawString(
        50,
        y,
        f"Start Date : {loan.start_date.strftime('%d %B %Y')}"
    )

    y -= 20

    pdf.drawString(
        50,
        y,
        f"Status : {loan.status.title()}"
    )

    y -= 35

    # ============================================
    # PAYMENT SUMMARY
    # ============================================

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(40, y, "Payment Summary")

    y -= 25

    pdf.setFont("Helvetica", 10)

    pdf.drawString(
        50,
        y,
        f"Total Repayment : {{ company.currency_symbol }}{loan.total_repayment():,.2f}"
    )

    y -= 20

    pdf.drawString(
        50,
        y,
        f"Amount Paid : {{ company.currency_symbol }}{loan.total_paid():,.2f}"
    )

    y -= 20

    pdf.drawString(
        50,
        y,
        f"Outstanding Balance : {{ company.currency_symbol }}{loan.balance():,.2f}"
    )

    y -= 40

    pdf.line(40, y, 555, y)

    y -= 25

    pdf.setFont("Helvetica-Bold", 11)

    pdf.drawString(
        40,
        y,
        "Recent Payments"
    )

    y -= 25

    pdf.setFont("Helvetica-Bold", 9)

    pdf.drawString(40, y, "Receipt")
    pdf.drawString(130, y, "Date")
    pdf.drawString(240, y, "Method")
    pdf.drawRightString(540, y, "Amount")

    y -= 12

    pdf.line(40, y, 555, y)

    y -= 18

    pdf.setFont("Helvetica", 9)

    payments = (
        Payment.objects
        .filter(loan=loan)
        .order_by("-payment_date")[:10]
    )

    if payments:

        for payment in payments:

            pdf.drawString(
                40,
                y,
                payment.receipt_number
            )

            pdf.drawString(
                130,
                y,
                payment.payment_date.strftime("%d-%m-%Y")
            )

            pdf.drawString(
                240,
                y,
                payment.get_method_display()
            )

            pdf.drawRightString(
                540,
                y,
                f"{{ company.currency_symbol }}{payment.amount_paid:,.2f}"
            )

            y -= 18

    else:

        pdf.drawString(
            40,
            y,
            "No payments have been made."
        )

    draw_footer(pdf, request)

    pdf.save()

    return response

def loan_register_pdf(request):

    loans = (
        Loan.objects
        .select_related("borrower")
        .order_by("-start_date")
    )

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        'attachment; filename="Loan_Register.pdf"'
    )

    pdf = canvas.Canvas(response)

    y = draw_header(pdf, "LOAN REGISTER")

    # ======================================
    # TABLE HEADER
    # ======================================

    pdf.setFont("Helvetica-Bold", 9)

    pdf.drawString(35, y, "ID")
    pdf.drawString(65, y, "Borrower")
    pdf.drawString(210, y, "Loan")
    pdf.drawString(300, y, "Paid")
    pdf.drawString(390, y, "Balance")
    pdf.drawString(490, y, "Status")

    y -= 12

    pdf.line(35, y, 560, y)

    y -= 15

    pdf.setFont("Helvetica", 8)

    total_loans = Decimal("0.00")
    total_paid = Decimal("0.00")
    total_balance = Decimal("0.00")
    total_records = 0

    for loan in loans:

        if y <= 80:

            draw_footer(pdf, request)

            pdf.showPage()

            y = draw_header(pdf, "LOAN REGISTER")

            pdf.setFont("Helvetica-Bold", 9)

            pdf.drawString(35, y, "ID")
            pdf.drawString(65, y, "Borrower")
            pdf.drawString(210, y, "Loan")
            pdf.drawString(300, y, "Paid")
            pdf.drawString(390, y, "Balance")
            pdf.drawString(490, y, "Status")

            y -= 12

            pdf.line(35, y, 560, y)

            y -= 15

            pdf.setFont("Helvetica", 8)

        borrower = (
            f"{loan.borrower.first_name} "
            f"{loan.borrower.last_name}"
        )

        pdf.drawString(35, y, str(loan.id))

        pdf.drawString(
            65,
            y,
            borrower[:24]
        )

        pdf.drawRightString(
            285,
            y,
            f"{{ company.currency_symbol }}{loan.loan_amount:,.2f}"
        )

        pdf.drawRightString(
            375,
            y,
            f"{{ company.currency_symbol }}{loan.total_paid():,.2f}"
        )

        pdf.drawRightString(
            470,
            y,
            f"{{ company.currency_symbol }}{loan.balance():,.2f}"
        )

        pdf.drawString(
            490,
            y,
            loan.status.title()
        )

        total_loans += loan.loan_amount
        total_paid += loan.total_paid()
        total_balance += loan.balance()
        total_records += 1

        y -= 18

    # ======================================
    # SUMMARY
    # ======================================

    y -= 15

    pdf.line(35, y, 560, y)

    y -= 20

    pdf.setFont("Helvetica-Bold", 10)

    pdf.drawString(40, y, f"Total Loans : {total_records}")

    y -= 18

    pdf.drawString(
        40,
        y,
        f"Loan Portfolio : {{ company.currency_symbol }}{total_loans:,.2f}"
    )

    y -= 18

    pdf.drawString(
        40,
        y,
        f"Total Recovered : {{ company.currency_symbol }}{total_paid:,.2f}"
    )

    y -= 18

    pdf.drawString(
        40,
        y,
        f"Outstanding Balance : {{ company.currency_symbol }}{total_balance:,.2f}"
    )

    draw_footer(pdf, request)

    pdf.save()

    return response

def payment_register_pdf(request):

    payments = (
        Payment.objects
        .select_related("loan", "loan__borrower")
        .order_by("-payment_date", "-id")
    )

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        'attachment; filename="Payment_Register.pdf"'
    )

    pdf = canvas.Canvas(response)

    y = draw_header(pdf, "PAYMENT REGISTER")

    # =====================================
    # TABLE HEADER
    # =====================================

    pdf.setFont("Helvetica-Bold", 8)

    pdf.drawString(35, y, "Receipt")
    pdf.drawString(110, y, "Date")
    pdf.drawString(180, y, "Borrower")
    pdf.drawString(340, y, "Method")
    pdf.drawString(420, y, "Loan")
    pdf.drawString(540, y, "Amount")

    y -= 12

    pdf.line(35, y, 560, y)

    y -= 15

    pdf.setFont("Helvetica", 8)

    total_collections = Decimal("0.00")
    total_transactions = 0

    for payment in payments:

        if y <= 80:

            draw_footer(pdf, request)

            pdf.showPage()

            y = draw_header(pdf, "PAYMENT REGISTER")

            pdf.setFont("Helvetica-Bold", 8)

            pdf.drawString(35, y, "Receipt")
            pdf.drawString(110, y, "Date")
            pdf.drawString(180, y, "Borrower")
            pdf.drawString(340, y, "Method")
            pdf.drawString(420, y, "Loan")
            pdf.drawString(540, y, "Amount")

            y -= 12

            pdf.line(35, y, 560, y)

            y -= 15

            pdf.setFont("Helvetica", 8)

        borrower = (
            f"{payment.loan.borrower.first_name} "
            f"{payment.loan.borrower.last_name}"
        )

        pdf.drawString(
            35,
            y,
            payment.receipt_number
        )

        pdf.drawString(
            110,
            y,
            payment.payment_date.strftime("%d-%m-%Y")
        )

        pdf.drawString(
            180,
            y,
            borrower[:24]
        )

        pdf.drawString(
            340,
            y,
            payment.get_method_display()
        )

        pdf.drawString(
            430,
            y,
            str(payment.loan.id)
        )

        pdf.drawRightString(
            555,
            y,
            f"{{ company.currency_symbol }}{payment.amount_paid:,.2f}"
        )

        total_collections += payment.amount_paid
        total_transactions += 1

        y -= 18

    # =====================================
    # SUMMARY
    # =====================================

    y -= 10

    pdf.line(35, y, 560, y)

    y -= 20

    pdf.setFont("Helvetica-Bold", 10)

    pdf.drawString(
        40,
        y,
        f"Total Transactions : {total_transactions}"
    )

    y -= 18

    pdf.drawString(
        40,
        y,
        f"Total Collections : {{ company.currency_symbol }}{total_collections:,.2f}"
    )

    draw_footer(pdf, request)

    pdf.save()

    return response

def borrowers_pdf(request):

    borrowers = Borrower.objects.order_by("first_name", "last_name")

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        'attachment; filename="Borrowers_Report.pdf"'
    )

    pdf = canvas.Canvas(response)

    y = draw_header(pdf, "BORROWERS REPORT")

    pdf.setFont("Helvetica-Bold", 8)

    pdf.drawString(30, y, "ID")
    pdf.drawString(60, y, "Name")
    pdf.drawString(210, y, "Phone")
    pdf.drawString(300, y, "BVN")
    pdf.drawString(410, y, "NIN")
    pdf.drawString(520, y, "Status")

    y -= 12

    pdf.line(30, y, 560, y)

    y -= 15

    pdf.setFont("Helvetica", 8)

    total = 0

    for borrower in borrowers:

        if y <= 80:

            draw_footer(pdf, request)

            pdf.showPage()

            y = draw_header(pdf, "BORROWERS REPORT")

            pdf.setFont("Helvetica-Bold", 8)

            pdf.drawString(30, y, "ID")
            pdf.drawString(60, y, "Name")
            pdf.drawString(210, y, "Phone")
            pdf.drawString(300, y, "BVN")
            pdf.drawString(410, y, "NIN")
            pdf.drawString(520, y, "Status")

            y -= 12

            pdf.line(30, y, 560, y)

            y -= 15

            pdf.setFont("Helvetica", 8)

        pdf.drawString(30, y, str(borrower.id))

        pdf.drawString(
            60,
            y,
            f"{borrower.first_name} {borrower.last_name}"[:24]
        )

        pdf.drawString(
            210,
            y,
            borrower.phone or "-"
        )

        pdf.drawString(
            300,
            y,
            (borrower.bvn or "-")[:15]
        )

        pdf.drawString(
            410,
            y,
            (borrower.nin or "-")[:15]
        )

        pdf.drawString(
            520,
            y,
            "Active"
        )

        total += 1

        y -= 18

    y -= 20

    pdf.setFont("Helvetica-Bold", 10)

    pdf.drawString(
        40,
        y,
        f"TOTAL BORROWERS : {total}"
    )

    draw_footer(pdf, request)

    pdf.save()

    return response

def defaulters_pdf(request):

    loans = (
        Loan.objects
        .select_related("borrower")
        .filter(status="overdue")
        .order_by("borrower__first_name")
    )

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        'attachment; filename="Defaulters_Report.pdf"'
    )

    pdf = canvas.Canvas(response)

    y = draw_header(pdf, "DEFAULTERS REPORT")

    pdf.setFont("Helvetica-Bold", 8)

    pdf.drawString(30, y, "Loan")
    pdf.drawString(70, y, "Borrower")
    pdf.drawString(210, y, "Phone")
    pdf.drawRightString(340, y, "Loan")
    pdf.drawRightString(420, y, "Paid")
    pdf.drawRightString(510, y, "Balance")

    y -= 12

    pdf.line(30, y, 560, y)

    y -= 15

    pdf.setFont("Helvetica", 8)

    total_defaulters = 0
    total_outstanding = Decimal("0.00")

    for loan in loans:

        if y <= 80:

            draw_footer(pdf, request)

            pdf.showPage()

            y = draw_header(pdf, "DEFAULTERS REPORT")

            pdf.setFont("Helvetica-Bold", 8)

            pdf.drawString(30, y, "Loan")
            pdf.drawString(70, y, "Borrower")
            pdf.drawString(210, y, "Phone")
            pdf.drawRightString(340, y, "Loan")
            pdf.drawRightString(420, y, "Paid")
            pdf.drawRightString(510, y, "Balance")

            y -= 12

            pdf.line(30, y, 560, y)

            y -= 15

            pdf.setFont("Helvetica", 8)

        borrower = (
            f"{loan.borrower.first_name} "
            f"{loan.borrower.last_name}"
        )

        balance = loan.balance()

        pdf.drawString(30, y, str(loan.id))

        pdf.drawString(
            70,
            y,
            borrower[:24]
        )

        pdf.drawString(
            210,
            y,
            loan.borrower.phone or "-"
        )

        pdf.drawRightString(
            340,
            y,
            f"{{ company.currency_symbol }}{loan.loan_amount:,.2f}"
        )

        pdf.drawRightString(
            420,
            y,
            f"{{ company.currency_symbol }}{loan.total_paid():,.2f}"
        )

        pdf.drawRightString(
            510,
            y,
            f"{{ company.currency_symbol }}{balance:,.2f}"
        )

        total_defaulters += 1
        total_outstanding += balance

        y -= 18

    y -= 20

    pdf.line(30, y, 560, y)

    y -= 20

    pdf.setFont("Helvetica-Bold", 10)

    pdf.drawString(
        40,
        y,
        f"TOTAL DEFAULTERS : {total_defaulters}"
    )

    y -= 18

    pdf.drawString(
        40,
        y,
        f"TOTAL OUTSTANDING : {{ company.currency_symbol }}{total_outstanding:,.2f}"
    )

    draw_footer(pdf, request)

    pdf.save()

    return response

def weekly_collection_pdf(request):

    today = timezone.now().date()
    start = today - timedelta(days=6)

    payments = (
        Payment.objects
        .filter(payment_date__range=[start, today])
        .order_by("payment_date")
    )

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        f'attachment; filename="Weekly_Collection_{today}.pdf"'
    )

    pdf = canvas.Canvas(response)

    y = draw_header(pdf, "WEEKLY COLLECTION REPORT")

    pdf.setFont("Helvetica-Bold", 9)

    pdf.drawString(40, y, "Date")
    pdf.drawString(180, y, "Transactions")
    pdf.drawRightString(540, y, "Collections")

    y -= 12
    pdf.line(40, y, 555, y)

    y -= 18

    total = Decimal("0.00")

    for i in range(7):

        day = start + timedelta(days=i)

        daily = payments.filter(payment_date=day)

        amount = (
            daily.aggregate(
                total=Sum("amount_paid")
            )["total"]
            or Decimal("0.00")
        )

        count = daily.count()

        pdf.drawString(
            40,
            y,
            day.strftime("%A %d %b %Y")
        )

        pdf.drawString(
            200,
            y,
            str(count)
        )

        pdf.drawRightString(
            540,
            y,
            f"{{ company.currency_symbol }}{amount:,.2f}"
        )

        total += amount

        y -= 20

    y -= 10

    pdf.line(40, y, 555, y)

    y -= 20

    pdf.setFont("Helvetica-Bold", 11)

    pdf.drawString(
        40,
        y,
        "TOTAL WEEKLY COLLECTION"
    )

    pdf.drawRightString(
        540,
        y,
        f"{{ company.currency_symbol }}{total:,.2f}"
    )

    draw_footer(pdf, request)

    pdf.save()

    return response

def monthly_financial_report_pdf(request):

    today = timezone.now().date()

    loans = Loan.objects.filter(
        start_date__year=today.year,
        start_date__month=today.month,
    )

    payments = Payment.objects.filter(
        payment_date__year=today.year,
        payment_date__month=today.month,
    )

    response = HttpResponse(content_type="application/pdf")

    response["Content-Disposition"] = (
        f'Monthly_Financial_Report_{today}.pdf'
    )

    pdf = canvas.Canvas(response)

    y = draw_header(pdf, "MONTHLY FINANCIAL REPORT")

    loans_disbursed = (
        loans.aggregate(
            total=Sum("loan_amount")
        )["total"]
        or Decimal("0.00")
    )

    collections = (
        payments.aggregate(
            total=Sum("amount_paid")
        )["total"]
        or Decimal("0.00")
    )

    outstanding = sum(
        loan.balance()
        for loan in Loan.objects.all()
    )

    active = Loan.objects.filter(
        status="active"
    ).count()

    completed = Loan.objects.filter(
        status="completed"
    ).count()

    overdue = Loan.objects.filter(
        status="overdue"
    ).count()

    borrowers = Borrower.objects.count()

    pdf.setFont("Helvetica-Bold", 11)

    pdf.drawString(40, y, "Financial Summary")

    y -= 30

    pdf.setFont("Helvetica", 10)

    rows = [

        ("Loans Disbursed", f"{{ company.currency_symbol }}{loans_disbursed:,.2f}"),

        ("Collections Received", f"{{ company.currency_symbol }}{collections:,.2f}"),

        ("Outstanding Portfolio", f"{{ company.currency_symbol }}{outstanding:,.2f}"),

        ("Active Loans", str(active)),

        ("Completed Loans", str(completed)),

        ("Overdue Loans", str(overdue)),

        ("Registered Borrowers", str(borrowers)),

    ]

    for title, value in rows:

        pdf.drawString(
            50,
            y,
            title
        )

        pdf.drawRightString(
            540,
            y,
            value
        )

        y -= 22

    draw_footer(pdf, request)

    pdf.save()

    return response