# Generated by Django 6.0.4 on 2026-07-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0005_alter_auditlog_user_alter_payment_loan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='duration_months',
            new_name='duration_weeks',
        ),
    ]
