# Generated by Django 6.0.4 on 2026-07-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0006_rename_duration_months_loan_duration_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymentschedule',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
