# Generated by Django 6.0.4 on 2026-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0007_repaymentschedule_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
