# Generated by Django 6.0.4 on 2026-07-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0008_alter_repaymentschedule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('currency_symbol', models.CharField(default='₦', max_length=10)),
                ('receipt_prefix', models.CharField(default='CWLS', max_length=20)),
                ('report_footer', models.TextField(default='Thank you for choosing CountryWide Lending & Services.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
