# Generated by Django 6.0.4 on 2026-07-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0011_systembackup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systembackup',
            options={'ordering': ['-created_at'], 'verbose_name': 'System Backup', 'verbose_name_plural': 'System Backups'},
        ),
        migrations.AddField(
            model_name='systembackup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('restored', 'Restored')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='systembackup',
            name='backup_type',
            field=models.CharField(choices=[('database', 'Database'), ('media', 'Media'), ('full', 'Full Project'), ('mysql', 'MySQL Database')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='systembackup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systembackup',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
